

exec-once = $HOME/.config/hypr/initial-boot.sh

### Sourcing external config files ###
$configs = $HOME/.config/hypr/configs # Default Configs directory path
$hyprland = $HOME/.config/hypr/hyprland
$scripts = $HOME/.config/hypr/scripts

source = $hyprland-old/keybindings.conf
source= $hyprland-old/startup.conf 
source= $hyprland-old/env.conf
source= $hyprland-old/window-rules.conf
source= $hyprland-old/general.conf

# Wallpaper
# exec = awww img ~/Pictures/wallpaper/wallpaper.GIF --transition-step 5 --transition-fps 10 --transition-type simple
