
# ██╗░░██╗██╗░░░██╗██████╗░██████╗░██╗░░░░░░█████╗░███╗░░██╗██████╗░
# ██║░░██║╚██╗░██╔╝██╔══██╗██╔══██╗██║░░░░░██╔══██╗████╗░██║██╔══██╗
# ███████║░╚████╔╝░██████╔╝██████╔╝██║░░░░░███████║██╔██╗██║██║░░██║
# ██╔══██║░░╚██╔╝░░██╔═══╝░██╔══██╗██║░░░░░██╔══██║██║╚████║██║░░██║
# ██║░░██║░░░██║░░░██║░░░░░██║░░██║███████╗██║░░██║██║░╚███║██████╔╝
# ╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░░░░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝╚═╝░░╚══╝╚═════╝░ 


env = XDG_CURRENT_DESKTOP,Hyprland   

# hyprlang if !XDG_DATA_HOME
$XDG_DATA_HOME = $HOME/.local/share
# hyprlang endif

# hyprlang if !XDG_CONFIG_HOME
$XDG_CONFIG_HOME = $HOME/.config
# hyprlang endif

$CONFIG_ALREADY_LOADED = true


#? Variables
source = ./variables.conf

#? Migration handling
# source = ./migration.conf

#? Default values
source = ./defaults.conf

#? Window rules
source = ./windowrules.conf

#? Environment variable Setup
source = ./env.conf

#? Dynamic Stuff example theming and variable handlings
source = ./dynamic.conf

# hyprlang if SCREEN_SHADER_COMPILED
decoration:screen_shader = $SCREEN_SHADER_COMPILED #! This is the compiled shader file, it will be created by the shaders.sh script
# hyprlang endif

#? HyDE's startup overridable too!
source = ./startup.conf

#? user now can have this file
source = $XDG_CONFIG_HOME/hypr/hyprland.conf  

#? workflows configuration overrides everything
source = $XDG_CONFIG_HOME/hypr/workflows.conf

#? finalized all variables as hyde properties 'hyde:variable'. This is faster to query than dynamic variables  
source = ./finale.conf

