[services]
gog = True
egs = True
ea_app = True
ubisoft = True
steam = True

[lutris]
library_ignores = 
migration_version = 16
width = 2048
height = 1232
maximized = True
selected_category = service:egs
icon_type_gridview_gog = banner
icon_type_gridview = coverart_med

