
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░


#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 1
    force_no_accel = 0
    accel_profile = flat 
    numlock_by_default = false

    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = true
    }

}

# Set environmental variables
env = XDG_CURRENT_DESKTOP,Hyprland
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DECORATION,whitesur-gtk

# Heroic env variables
env = DRI_PRIME,1
env = __NV_PRIME_RENDER_OFFLOAD,1
env = VK_ICD_FILENAMES,/usr/share/vulkan/icd.d/nvidia_icd.json

# Grub
exec-shutdown = update-grub

# Wallpaper
# exec-once = mpvpaper --fork -o "--loop-playlist" ALL ~/.config/hypr/themes/assets/pain.webm 


