# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground                  #D4D4D4
background                  #161616
background-alt              rgba(28,28,28,0.25)
cursor                      #6d6d6d

active_tab_foreground       #161616
active_tab_background       #D4D4D4
inactive_tab_foreground     #D4D4D4
inactive_tab_background     #161616

color0                      #6d6d6d
color1		                #c7c7c7
color2		                #c7c7c7
color3		                #c7c7c7
color4		                #c7c7c7
color5		                #c7c7c7
color6		                #c7c7c7
color7		                #c7c7c7
color8		                #c7c7c7
color9		                #c7c7c7
color10		                #c7c7c7
color11		                #c7c7c7
color12		                #c7c7c7
color13		                #c7c7c7
color14		                #c7c7c7
color15		                #c7c7c7
