# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground                  #D4D4D4
background                  #161616
background-alt              rgba(28,28,28,0.25)
cursor                      #6d6d6d

active_tab_foreground       #161616
active_tab_background       #D4D4D4
inactive_tab_foreground     #D4D4D4
inactive_tab_background     #161616

color0                      #6d6d6d
color1		                #6d6d6d
color2		                #6d6d6d
color3		                #6d6d6d
color4		                #6d6d6d
color5		                #6d6d6d
color6		                #6d6d6d
color7		                #6d6d6d
color8		                #6d6d6d
color9		                #6d6d6d
color10		                #6d6d6d
color11		                #6d6d6d
color12		                #6d6d6d
color13		                #6d6d6d
color14		                #6d6d6d
color15		                #6d6d6d
